runners:
 AWS-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic
  
jobs:   
 hello-world:
  resource_spec: micro
  runner: AWS-runner

  
  current_working_directory: ~/
  output:
   artifact:
    - hello.txt  
    - /root/artifact
  steps:
   - run:
      name: Install software
      command: |

       echo $(pwd)
       ls -a
       cd /tmp
       ls -a
       mkdir -p /root/artifact
       cp workflow*.tar.gz /root/artifact
       tar -xzf *.tar.gz
       apt-get update -y
       apt-get install iputils-ping -y
   - run:
      name: Say Hello World
      command: echo "Hello World" 
   - run:
      name: Text Hello World
      command: echo "Hello World" > hello.txt    
   - run:
      name: fail
      command: echo "ffffffffffff!"
   - run:
      name: Arabic 
      command: echo "Ø› ØŸ Ø¡ Ø¢ Ø£ Ø¤ Ø¥ Ø¦ Ø§ Ø¨ Ø© Øª Ø« Ø¬ Ø­ Ø® Ø¯ Ø° Ø± Ø² Ø³ Ø´ Øµ Ø¶ Ø· Ø¸ Ø¹ Øº Ù€ Ù Ù‚ Ùƒ Ù„ Ù… Ù† Ù‡ Ùˆ Ù‰ ÙŠ Ù‹ ÙŒ Ù Ù Ù Ù Ù‘ Ù’ Ù  Ù¡ Ù¢ Ù£ Ù¤ Ù¥ Ù¦ Ù§ Ù¨ Ù© Ùª Ù« Ù¬ Ù­ Ù° Ù± Ù² Ù³ Ù´ Ùµ Ù¶ Ù· Ù¸ Ù¹ Ùº Ù» Ù¼ Ù½ Ù¾ Ù¿ Ú€ Ú Ú‚ Úƒ Ú„ Ú… Ú† Ú‡ Úˆ Ú‰ ÚŠ Ú‹ ÚŒ Ú Ú Ú Ú Ú‘ Ú’ Ú“ Ú” Ú• Ú– Ú— Ú˜ Ú™ Úš Ú› Úœ Ú Ú ÚŸ Ú  Ú¡ Ú¢ Ú£ Ú¤ Ú¥ Ú¦ Ú§ Ú¨ Ú© Úª Ú« Ú¬ Ú­ Ú® Ú¯ Ú° Ú±"

   - run:
      name: Accented Latin 
      command: echo "Ä€ Ã Ä‚ Ã€ Ä Ã¡ Äƒ Ã  Ç• Ç— Ç™ Ç› Ç– Ç˜ Çš Çœ"
   - run:
      name: Accented Latin 
      command: echo "Ä€ Ã Ä‚ Ã€ Ä Ã¡ Äƒ Ã  Ç• Ç— Ç™ Ç› Ç– Ç˜ Çš Çœ"
   - run:
      name: Chinese 
      command: echo "æˆ‘ä»¬åˆšæ‰ä»å›¾ä¹¦é¦†æ¥äº†"
   - run:
      name: Rare Chinese character
      command: echo "ğ¦®™"
   - run:
      name: Russian
      command: echo "Ğ¯ Ğ½Ğµ Ğ³Ğ¾Ğ²Ğ¾Ñ€Ñ Ğ¿Ğ¾-Ñ€ÑƒÑÑĞºĞ¸"
   - run:
      name: Greek
      command: echo "Îœá¿†Î½Î¹Î½ á¼„ÎµÎ¹Î´Îµ Î¸Îµá½° Î Î·Î»Î·ÏŠÎ¬Î´ÎµÏ‰ á¼ˆÏ‡Î¹Î»á¿†Î¿Ï‚"
   - run:
      name: Hebrew
      command: echo "" ×× ×™ ×œ× ×œ×•××“ ×¢×‘×¨×™×ª "
   - run:
      name: Esperanto
      command: echo "Äˆ Ä‰ Äœ Ä Ä¤ Ä¥ Ä´ Äµ Åœ Å Å¬ Å­"
   - run:
      name: Hieroglyphics
      command: echo "ğ“‚ğ“ƒ€ğ“…¡ğ“„¿ğ“Œ‚ ğ“‹´ğ“…“ğ“ğ“‡ğ“‡Œğ“€€"
   - run:
      name: wait
      command: sleep 60     
      
workflows:
 hello-world-workflow:
  triggers:
   - manual 
   - push

  jobs:
   - hello-world